import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import './globals.css';
import Providers from '@/components/providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const beVietnamPro = Be_Vietnam_Pro({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-beVietnamPro',
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${beVietnamPro.variable} antialiased font-[family-name:var(--font-beVietnamPro)]`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
